FROM bcit/centos:7-latest

<%= snippet('labels', binding) -%>

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install <% image.vars['yum_build_deps'].each do |pkg| -%> \
    <%= pkg -%>
<% end -%>

CMD [ "init-loop" ]
